name: ItemLifeTime
version: 1.0.1
main: DavyCraft648\ItemLifeTime\Main
api: 5.0.0
description: Adjust the time of dropped items to disappear in your server
authors: [DavyCraft648,xDqZtop]
website: https://github.com/xDqZtop/ItemLifeTime
