# Default lifetime for dropped items (in seconds)
# - Default: 300 (5 minutes)
# - Range: 0 to 1938 (≈32 minutes)
# - Set to -1 to disable despawn completely
item-lifetime: 300

# Custom item lifetimes per world (optional)
# Format:
#   world-name: lifetime-in-seconds
# Example:
#   lobby: -1  # Items never despawn in lobby
#   pvp: 60    # 1 minute despawn in PvP arena
worlds: {}

# Display remaining time as item name tag
display-time:
  # Enable/disable time display
  enabled: false
  
  # Display format options:
  # Available placeholders:
  #   {SECOND} - Remaining seconds (00-59)
  #   {MINUTE} - Remaining minutes
  #   {TIME}   - Human-readable time (e.g. "1 minute 30 seconds")
  text: "{MINUTE}:{SECOND}"